[package]
name = "format-macro"
version = "0.1.0"
authors = ["John Renner <john@jrenner.net>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = {version = "0.15", features = ["full"]}
quote = "0.6"